#author: Mengwen Li
all: mli2_EnhancedEchoClient mli2_EnhancedEchoServer

mli2_EnhancedEchoClient: mli2_EnhancedEchoClient.cpp
	g++ -o mli2_EnhancedEchoClient mli2_EnhancedEchoClient.cpp

mli2_EnhancedEchoServer: mli2_EnhancedEchoServer.cpp
	g++ -o mli2_EnhancedEchoServer mli2_EnhancedEchoServer.cpp

clean:
	rm mli2_EnhancedEchoClient mli2_EnhancedEchoServer
