#author: Mengwen Li
all: mli2_EchoClient mli2_EchoServer

mli2_EchoClient: mli2_EchoClient.cpp 
	g++ -o mli2_EchoClient mli2_EchoClient.cpp

mli2_EchoServer: mli2_EchoServer.cpp
	g++ -o mli2_EchoServer mli2_EchoServer.cpp

clean:
	rm mli2_EchoClient mli2_EchoServer
